name: Feature Request
description: Suggest a feature for ThenJS
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you'd like.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.

  - type: dropdown
    id: package
    attributes:
      label: Package
      options:
        - thenjs
        - "@thenjs/server"
        - "@thenjs/rpc"
        - "@thenjs/schema"
        - "@thenjs/build"
        - "@thenjs/adapter-node"
        - "@thenjs/adapter-vercel"
        - create-then
        - New package
